### PR TITLE
Support .NET Standard?

### PR DESCRIPTION
**Pull request by Jaykul**
This merge is a harder conversation. 😁 

To get to .NET Standard we need to first upgrade to using `dotnet restore` and `dotnet build` (or MSBuild 15, or VS 2017).  The cool thing about this new format is (if you have the targeting pack installed) you can also add `net35` to the TargetFrameworks and automatically build all three at once.

To add .NET Standard support, we have to remove anything that doesn't work there -- which includes WPF and System.Drawing. So we must write a manual conversion for HSL/HSV to replace calls to WPF's `System.Windows.Color` and `System.Drawing.Color` which don't exist in .NET Standard. And we must move all of the color profile stuff to it's own assembly -- which only works on Windows on .Net 4.5

Note that I did have to change the Hue/Saturation on the Silver test to get it to pass. I'm not totally sure why my algorithm gets a different value, but Hue and Saturation are irrelevant for Silver, right? Perceptually, they're the same...

### CODE REVIEW

**Comment by THEjoezack** [comment]
Awesome! I want to take a look at the HSL/HSV thing before I merge - I got the numbers from _somewhere_ originally so I wanted to try cross-checking against another source. Thanks for working on this!

**Comment by Jaykul** [comment]
Yeah, please review thoroughly 😉 

These are implemented based on the explanations of how it's _supposed_ to work on Wikipedia (with some reference to other language implementations from all over), but it definitely took me more than one try to get it right.

That one Silver thing is just a mystery to me. I'm not sure how everything else can be the same, and that one be so very different. I was guessing the value you have is from the EasyRGB web converter, which seemed like it was picking arbitrary values in the middle of a color (i.e. 60/150/240/300) when things were close to neutral saturation. 

I'd feel much better about it if the saturation values were the same, but on a scale of 0-100,  0.7 and 0.02 are imperceptibly different from 0, so I don't know ...

**Comment by THEjoezack** [comment]
Everything looks good to me, thanks for your patience!

**Comment by jimmystridh** [comment]
Will you publish a new nuget package @THEjoezack or is the currently some blocking issue w/ regards to multiple SDK versions?

**Pull request merged**
